name: OWASP Dependency usando npx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # O la versi칩n de Node.js que uses en tu proyecto

      - name: Instalar dependencias de npm
        working-directory: ev1_frontend  # Cambia "demo" por el directorio donde est치 tu pom.xml
        run: npm install

      - name: Instalar OWASP Dependency-Check (como dependencia dev)
        working-directory: ev1_frontend  # Cambia "demo" por el directorio donde est치 tu pom.xml
        run: npm install --save-dev owasp-dependency-check
      - name: Setup Dependency-Check
        run: chmod +x dependency-check-bin/latest/dependency-check/bin/dependency-check.sh
      - name: Ejecutar OWASP Dependency-Check en el proyecto Node.js
        working-directory: ev1_frontend  # Cambia "demo" por el directorio donde est치 tu pom.xml
        run: npx owasp-dependency-check --project "node-project" --scan package-lock.json --out ./dependency-check-report --exclude ./dependency-check-bin --exclude ./node_modules --verbose 

      - name: Subir el reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report