name: Mox Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Instalar dependencias de npm
        working-directory: ev1_frontend  # Cambia "demo" por el directorio donde está tu pom.xml
        run: npm install
      - name: Descargar OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.0.0/dependency-check-8.0.0-release.zip
          unzip dependency-check-8.0.0-release.zip
          cd dependency-check

      - name: Ejecutar OWASP Dependency-Check
        run: |
          ./bin/dependency-check.sh --project "my-project" --scan . --out ./dependency-check-report

      - name: Subir el reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report