name: OWASP Dependency-Check for Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # O la versión de Node.js que uses en tu proyecto

      - name: Instalar dependencias de npm
        working-directory: ev1_frontend  # Cambia "demo" por el directorio donde está tu pom.xml
        run: npm install

      - name: Instalar OWASP Dependency-Check (como dependencia dev)
        working-directory: ev1_frontend  # Cambia "demo" por el directorio donde está tu pom.xml
        run: npm install --save-dev owasp-dependency-check

      - name: Ejecutar OWASP Dependency-Check en el proyecto Node.js
        run: npx owasp-dependency-check --project "node-project" --scan ev1_frontend/node_modules --out ./dependency-check-report

      - name: Subir el reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report